packages:
  - 'apps/frontend/*'
  - 'apps/backend/*'
  - 'packages/*'
allowBuilds:
  argon2: true
  sharp: true
  unrs-resolver: true

catalog:
  'react': ^19.0.0
  'react-dom': ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/node': 25.8.0
